# Ashell configuration
log_level = "warn"
outputs = "All"
position = "Top"

# Launchers
app_launcher_cmd = "rofi -show drun"
clipboard_cmd = "copyq menu | wl-copy"

[services.brightness]
enabled = false

[modules]
left = [ [ "appLauncher", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Tray", "Clock", "Privacy", "Settings" ] ]

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "rofi -show drun"

[window_title]
truncate_title_after_length = 100

[settings]
# Use swaylock-effects which is installed via modules
lock_cmd = "playerctl --all-players pause; swaylock-effects &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
# Use blueman (enabled in modules) instead of blueberry
bluetooth_more_cmd = "blueman-manager"

[appearance]
style = "Islands"
primary_color = "#ffffff"
success_color = "#b0b3ba"
text_color = "#f3f3f3"
workspace_colors = [ "#ffffff", "#b0b3ba" ]
special_workspace_colors = [ "#ffffff", "#b0b3ba" ]

[appearance.danger_color]
base = "#ff5555"
weak = "#ff8888"

[appearance.background_color]
base = "#23242a"
weak = "#2e2f36"
strong = "#44464d"

[appearance.secondary_color]
base = "#3a3b3f"